spring.application.name=videogamemanager

spring.data.mongodb.uri=mongodb+srv://javierlopeztl1_db_user:Uv1fMcsYFYLjRVA6@cluster0.xxxx.mongodb.net/gamevault?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true