# Configuración General
spring.application.name=videogamemanager
server.port=8081

# Configuración de MongoDB desglosada
# Usamos variables ${} que Spring buscará en el sistema
spring.data.mongodb.username=${DB_USER}
spring.data.mongodb.password=${DB_PASSWORD}
spring.data.mongodb.host=cluster0.jhtchy1.mongodb.net
spring.data.mongodb.database=gamevault
spring.data.mongodb.auto-index-creation=true

# Opciones adicionales para Atlas (necesarias en versiones recientes)
spring.data.mongodb.additional-params=retryWrites=true&w=majority