
spring.application.name=videogamemanager
server.port=8082

spring.data.mongodb.uri=mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.jhtchy1.mongodb.net/gamevault?retryWrites=true&w=majority
app.admin.token=${ADMIN_TOKEN:dev-token}